title: Luan Pena's Github Page
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: luanspl.github.io"" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Luan Pena # add your name
author-img: luan.jpg # add your photo
about-author: Electric Engineer and Programmer, I'm also an enthusiastic about Technology. # add description
social-twitter: # add your Twitter handle
social-facebook: luan.pena # add your Facebook handle
social-github: luanspl # add your Github handle
social-linkedin: luan-pena-569b1246/ # add your Linkedin handle
social-email: luan.gppcom@gmail.com # add your Email address

# Disqus
discus-identifier: luan_pena # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
